export const actionType={
    FETCH_ARTICLE:"FETCH_ARITCLE",
    DELETE_ARTICLE:"DELETE_ARTICLE",
    ADD_ARTICLE:"ADD_ARTICLE",
    CREATE_POST:"CREATE_POST",
    UPDATE_ARTICLE:"UPDATE_ARTICLE",
    ON_ADD:"ON_ADD",
    ON_EDIT:"ON_EDIT",
    VEIW_ARTICLE:"VEIW_ARTICEL",
    HANDLE_SHOW:"HANDLE_SHOW"
}